Rafadana/event participants
deco-freons/fe-mobile-flutter pull request #27
Opened 2022-09-04 05:42 UTC by RafadanaM

### Background: 
Adding participants list page

### Additional Packages/Dependencies:
- none

### Changes:

### How to Implement:
- none

2022-09-04 08:36 UTC, YafiAhsanH requested changes

2022-09-04 08:36 UTC, YafiAhsanH commented on lib/app.dart
> +                  EventDetail.routeName,
you forgot to change this back to location permission

2022-09-04 08:36 UTC, YafiAhsanH commented on lib/common/components/buttons/back_button.dart
> +  final VoidCallback onPressesed;
little typo, onPressed

2022-09-04 08:36 UTC, YafiAhsanH commented on lib/common/components/buttons/custom_back_button.dart
> +  @override
there are two back button components (BackButton and CustomBackButton) are they both being used?

2022-09-04 08:36 UTC, YafiAhsanH commented on lib/event/components/participant_card.dart
> +        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
border radius 20 can use the custom border radius

2022-09-04 08:36 UTC, YafiAhsanH commented on lib/page/email_confirmation.dart
>  import 'package:flutter_boilerplate/page/landing.dart';
u forgot to delete the empty lines

2022-09-04 23:21 UTC, YafiAhsanH approved these changes
looks good!

2022-09-05 02:44 UTC, oliver-mf approved these changes
Looks gud to me

2022-09-05 03:42 UTC, merged