Oliver/dropdown component
deco-freons/fe-mobile-flutter pull request #33
Opened 2022-09-10 06:45 UTC by oliver-mf

### Background: 
- create custom dropdown button component

### Additional Packages/Dependencies:
- none

### Changes:
- lib/common/components/buttons/custom_dropdown_button.dart
- lib/event/bloc/search_event/popular_events_cubit.dart
- lib/page/event_detail.dart
- lib/page/homepage.dart

2022-09-11 09:16 UTC, RafadanaM requested changes

2022-09-11 09:16 UTC, RafadanaM commented on lib/page/homepage.dart
> +    for (var radius in radiusOptions) {
Seperate the array to another file instead of  filling it in init state

2022-09-12 09:19 UTC, RafadanaM approved these changes

2022-09-12 09:20 UTC, suryanirvana approved these changes
![6qpv6x](https://user-images.githubusercontent.com/41690774/189618310-a2ea19ea-d80c-4cd4-9de5-761caa5e9aab.jpg)

2022-09-12 09:20 UTC, merged

2022-09-12 09:22 UTC, YafiAhsanH approved these changes
Looks good!