Oliver/event matching homepage
deco-freons/fe-mobile-flutter pull request #37
Opened 2022-09-17 10:23 UTC by oliver-mf

### Background: 
- create homepage event matching card

### Additional Packages/Dependencies:
- none

### Changes:
-

2022-09-17 13:41 UTC, suryanirvana requested changes
change API

2022-09-18 09:23 UTC, RafadanaM approved these changes

2022-09-18 12:59 UTC, YafiAhsanH approved these changes
Looks good to me!

2022-09-19 09:28 UTC, suryanirvana approved these changes

2022-09-19 09:29 UTC, merged